sonar.projectKey=shopkart-devsecops
sonar.projectName=ShopKart DevSecOps

sonar.sources=services

sonar.tests=services

sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts

sonar.javascript.lcov.reportPaths=services/auth-service/coverage/lcov.info,services/catalog-service/coverage/lcov.info,services/order-service/coverage/lcov.info
