sonar.projectKey=shopkart-devsecops
sonar.projectName=ShopKart DevSecOps

sonar.sources=services
sonar.tests=services

sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.javascript.lcov.reportPaths=services/auth-service/coverage/lcov.info,services/catalog-service/coverage/lcov.info,services/order-service/coverage/lcov.info
