apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopkart-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/maheshkumar198/shopkart-devsecops.git
    targetRevision: develop
    path: helm/shopkart

    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: shopkart-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true