apiVersion: v1
kind: Service

metadata:
  namespace: {{ .Values.namespace }}
  name: auth-service
  labels:
    app: auth-service

spec:
  selector:
    app: {{ .Release.Name }}-auth

  ports:
    - port: {{ .Values.auth.port }}
      targetPort: {{ .Values.auth.port }}

  type: ClusterIP