apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: {{ .Values.namespace }}
  labels:
    app: catalog-service
spec:
  type: ClusterIP

  selector:
    app: {{ .Release.Name }}-catalog

  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP