apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: {{ .Values.ClusterSecretStore.aws.secretStoreName }}

spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.ClusterSecretStore.aws.region }}

      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.ClusterSecretStore.aws.serviceAccount.name }}
            namespace: {{ .Values.ClusterSecretStore.aws.serviceAccount.namespace }}