apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ .Values.externalSecrets.db.secretName }}
  namespace: {{ .Values.namespace }}

spec:
  refreshInterval: {{ .Values.externalSecrets.db.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecrets.aws.secretStoreName }}
    kind: ClusterSecretStore

  target:
    name: {{ .Values.externalSecrets.db.secretName }}
    creationPolicy: Owner

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.externalSecrets.db.remoteKey }}
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.db.remoteKey }}
        property: password