apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.jwt.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.jwt.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.aws.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.jwt.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.jwt.remoteKey }}
        property: JWT_SECRET