apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-service
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.order.replicas }}

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      containers:
        - name: order-service

          image: "{{ .Values.order.image.repository }}:{{ .Values.order.image.tag }}"

          imagePullPolicy: {{ .Values.order.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.order.port }}

          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: shopkart-config
                  key: NODE_ENV

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: shopkart-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: shopkart-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: shopkart-config
                  key: DB_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shopkart-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopkart-db-secret
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopkart-secret
                  key: JWT_SECRET

          resources:
            {{- toYaml .Values.order.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.order.port }}
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.order.port }}
            initialDelaySeconds: 20
            periodSeconds: 20