namespace: shopkart-dev

config:
  NODE_ENV: production
  DB_HOST: shopkart-dev-postgres.c7qqm8eoycgr.ap-south-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: shopkart

externalSecrets:
  aws:
    secretStoreName: aws-secrets-manager

  db:
    secretName: shopkart-db-secret
    refreshInterval: 1h
    remoteKey: "arn:aws:secretsmanager:ap-south-1:905179308072:secret:rds!db-fd3db08c-32ec-4f74-a2a5-5808f15b8c79-IPmdIo"
