server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /api/auth/ {
    proxy_pass http://auth-service:3001/auth/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/products {
    proxy_pass http://catalog-service:3002/products;
    proxy_set_header Host $host;
  }

  location /api/cart {
    proxy_pass http://order-service:3003/cart;
    proxy_set_header Host $host;
  }

  location /api/orders {
    proxy_pass http://order-service:3003/orders;
    proxy_set_header Host $host;
  }
}
